opora/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from .tasks import *
from .views import TranscriptionView
from .tasks import *  # Keep it to make Moonsheep aware of defined tasks

from moonsheep.exporters.api import AppApi
from moonsheep.views import ChooseNicknameView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^moonsheep/', include('moonsheep.urls')),
    url(r'^$', TemplateView.as_view(template_name='homepage.html'), name='finish-transcription'),
    url(r'^$', TemplateView.as_view(template_name='homepage.html'), name='home'),
    url(r'^transcription/$', TranscriptionView.as_view(), name='transcription'),
    path('get-a-nickname', ChooseNicknameView.as_view(template_name='nickname.html'), name='choose-nickname'),
    url(r'^thank-you/$', TemplateView.as_view(template_name='thankyou.html'), name='thank-you'),

    path('api/opora/', include(AppApi('opora').urls)),
    url(r'^api-auth/', include('rest_framework.urls'))
]


# DEV-DEBUG
from django.conf import settings
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

opora/forms.py
from django import forms

from moonsheep.forms import MultipleRangeField

from . import models


class FindTableForm(forms.Form):
    party_name = forms.CharField(label="Party name", initial='')
    party_legal_id = forms.CharField(label="Party legal ID", initial='')  # TODO in model it is int, what it should be?
    date = forms.DateField(label="Report date")

    class Meta:
        localized_fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(FindTableForm, self).__init__(*args, **kwargs)
        for md, tt, li in models.TransactionPages.iterations():
            idx = '{0}{1}{2}'.format(md, tt, li)
            self.fields['no_pages_{0}'.format(idx)] = \
                forms.BooleanField(label="No pages", required=False,
                                   widget=forms.CheckboxInput(attrs={'class': "form-check-input"}))
            self.fields['page_start_{0}'.format(idx)] = \
                forms.IntegerField(label="First page number", required=False)
            self.fields['page_end_{0}'.format(idx)] = \
                forms.IntegerField(label="Last page number", required=False)
            self.fields['total_funds_{0}'.format(idx)] = \
                forms.CharField(label="Total received funds", required=False, initial='')

    def clean(self):
        cleaned_data = super(FindTableForm, self).clean()

        for md, tt, li in models.TransactionPages.iterations():
            idx = '{0}{1}{2}'.format(md, tt, li)
            page_start = cleaned_data.get("page_start_{0}".format(idx))
            page_end = cleaned_data.get("page_end_{0}".format(idx))
            total_funds = cleaned_data.get("total_funds_{0}".format(idx))
            no_pages = cleaned_data.get("no_pages_{0}".format(idx))
            if not bool(no_pages):
                # Check if all data provided
                if not (bool(page_start) and bool(page_end) and total_funds is not None):
                    self.add_error('no_pages_' + idx, forms.ValidationError("Fill in all data for this table or say it "
                                                                         "doesn't exist."))
                else:
                    if page_end < page_start:
                        self.add_error('no_pages_' + idx, forms.ValidationError("Last page must be greater or equal than "
                                                                         "first page."))
                    if page_start < 1:
                        self.add_error('no_pages_' + idx,
                                       forms.ValidationError("Page must be a positive number."))
            else:
                cleaned_data['page_end_' + idx] = None
                cleaned_data['page_start_' + idx] = None
                cleaned_data['page_total_funds_' + idx] = None

        if self.errors:
            raise forms.ValidationError("Please correct errors below.")

        return cleaned_data


class GetTransactionIdsForm(forms.Form):
    transaction_ids = MultipleRangeField(label="Transaction IDs")

    class Meta:
        localized_fields = '__all__'


class GetTransactionForm(forms.Form):
    receipt_date = forms.DateField(label="Receipt date")
    amount = forms.CharField(label="Transaction amount")
    # payee
    payee_name = forms.CharField(label="Payee name")
    payee_identification = forms.CharField(label="Payee identification", required=False)
    payee_address = forms.CharField(label="Payee address")

    class Meta:
        localized_fields = '__all__'


class GetDonationForm(GetTransactionForm):
    account_type = forms.CharField(label="Account type")

    class Meta:
        localized_fields = '__all__'


class GetReturnForm(GetTransactionForm):
    date = forms.DateField(label="Return date")
    document_id = forms.CharField(label="Return document ID")
    explanation = forms.CharField(label="Return explanation")
    amount_to_payee = forms.CharField(label="Return amount to payee")
    amount_to_state_budget = forms.CharField(label="Return amount to state budget")

    class Meta:
        localized_fields = '__all__'

templates/tasks/base_form.html
{% extends "transcription.html" %}

{% load static %}
{% load i18n %}
{% load moonsheep %}

{% block content %}
<div id="task">
  {% block task-fill %}
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
    {% endif %}
  <form id="taskForm" action="#" method="post">
    {% csrf_token %}
    {% moonsheep_token task %}
    <div class="row-fluid">
      <div class="col-md-12">
        {% if debug %}DEBUG: Current task class/id: {{ task.id }}{% endif %}
      {% block task-form %}
      {% endblock %}
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-md-6 col-md-offset-3 text-center">
        <button type="submit" class="button large-button" style="display:inline-block;" name="_action" value="save">уявити</button>

        <button type="submit" class="button large-button" style="display:inline-block;" name="_action" value="skip"
          formnovalidate="formnovalidate">{% trans "Skip to next" %}</button>
        <button type="submit" class="button large-button" style="display:inline-block;" name="_action" value="cancel"
          formnovalidate="formnovalidate">{% trans "Cancel" %}</button>
      </div>
    </div>
  </form>
  {% endblock %}
</div>
{% endblock %}

{% block scripts %}
  <script type="application/javascript" src="{% static "js/api/transcript.js" %}"></script>
{% endblock %}

templates/tasks/get_donation.html
{% extends "tasks/base_form.html" %}

{% block task-form %}
<h3>Scroll the document to page {{ task.params.page }}. Find transaction (donation) with bank ID = {{ task.params.transaction_id }} and rewrite it:</h3>

<section class="row" id="section1-1">
<div class="col-md-12">
  <div class="table-wrapper">
    <table class="table sevencols">
      <thead>
        <tr>
          <th class="form-group{% if form.errors.receipt_date %} has-error{% endif %}">
            <label class="control-label" for="id_receipt_date">
              Дата надходження внеску
            </label>
          </th>
          <th class="form-group{% if form.errors.account_type %} has-error{% endif %}">
            <label class="control-label" for="id_account_type">
              Вид рахунку
            </label>
          </th>
          <th class="form-group{% if form.errors.transaction_id %} has-error{% endif %}">
            <label class="control-label" for="id_transaction_id">
              Номер розрахункового документа
            </label>
          </th>
          <th class="form-group{% if form.errors.payee_name %} has-error{% endif %}">
            <label class="control-label" for="id_payee_name">
              Прізвище, ім’я, по батькові платника
            </label>
          </th>
          <th class="form-group{% if form.errors.payee_identification %} has-error{% endif %}">
            <label class="control-label" for="id_payee_identification">
              РНОКПП або серія та номер паспорта з відміткою
            </label>
          </th>
          <th class="form-group{% if form.errors.payee_address %} has-error{% endif %}">
            <label class="control-label" for="id_payee_address">
              Місце проживання платника
            </label>
          </th>
          <th class="form-group{% if form.errors.amount %} has-error{% endif %}">
            <label class="control-label" for="id_amount">
              Сума (грн)
            </label>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr class="replicator">
          <td class="form-group{% if form.errors.receipt_date %} has-error{% endif %}">
            <input type="date" class="form-control input-sm" id="id_receipt_date" name="receipt_date">
            {% if form.errors.receipt_date %}<span class="help-block">{{ form.errors.receipt_date }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.account_type %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_account_type" name="account_type">
            {% if form.errors.account_type %}<span class="help-block">{{ form.errors.account_type }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.transaction_id %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_transaction_id" value="{{ task.params.transaction_id }}" disabled>
            {% if form.errors.transaction_id %}<span class="help-block">{{ form.errors.transaction_id }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.payee_name %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_payee_name" name="payee_name">
            {% if form.errors.payee_name %}<span class="help-block">{{ form.errors.payee_name }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.payee_identification %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_payee_identification" name="payee_identification">
            {% if form.errors.payee_identification %}<span class="help-block">{{ form.errors.payee_identification }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.payee_address %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_payee_address" name="payee_address">
            {% if form.errors.payee_address %}<span class="help-block">{{ form.errors.payee_address }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.amount %} has-error{% endif %}">
            <input type="text" class="form-control input-sm last" id="id_amount" name="amount">
            {% if form.errors.amount %}<span class="help-block">{{ form.errors.amount }}</span>{% endif %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
</section>
{% endblock %}

templates/tasks/get_return.html
{% extends "tasks/base_form.html" %}

{% block task-form %}
<h3>Scroll the document to page {{ task.params.page }}. Find transaction (return) with bank ID = {{ task.params.transaction_id }} and rewrite it:</h3>

<section class="row" id="section1-1">
<div class="col-md-12">
  <div class="table-wrapper">
    <table class="table sevencols">
      <thead>
        <tr>
          <th class="form-group{% if form.errors.receipt_date %} has-error{% endif %}">
            <label class="control-label" for="id_receipt_date">
                Дата надходження внеску
            </label>
          </th>
          <th class="form-group{% if form.errors.amount %} has-error{% endif %}">
            <label class="control-label" for="id_amount">
              Загальна сума коштів
            </label>
          </th>
          <th class="form-group{% if form.errors.transaction_id %} has-error{% endif %}">
            <label class="control-label" for="id_transaction_id">
              Номер розрахункового документа
            </label>
          </th>
          <th class="form-group{% if form.errors.payee_name %} has-error{% endif %}">
            <label class="control-label" for="id_payee_name">
              Прізвище, ім’я, по батькові особи, від якої отримано кошти
            </label>
          </th>
          <th class="form-group{% if form.errors.payee_identification %} has-error{% endif %}">
            <label class="control-label" for="id_payee_identification">
              РНОКПП або серія та номер паспорта з відміткою
            </label>
          </th>
          <th class="form-group{% if form.errors.payee_address %} has-error{% endif %}">
            <label class="control-label" for="id_payee_address">
              Місце проживання особи
            </label>
          </th>
          <th class="form-group{% if form.errors.date %} has-error{% endif %}">
            <label class="control-label" for="id_date">
              Дата повер-нення
            </label>
          </th>
          <th class="form-group{% if form.errors.document_id %} has-error{% endif %}">
            <label class="control-label" for="id_document_id">
              Номер розрахунково-го документа
            </label>
          </th>
          <th class="form-group{% if form.errors.explanation %} has-error{% endif %}">
            <label class="control-label" for="id_explanation">
              Обґрунтува-ння повернення
            </label>
          </th>
          <th class="form-group{% if form.errors.amount_to_payee %} has-error{% endif %}">
            <label class="control-label" for="id_amount_to_payee">
              Сума повернення (грн)
            </label>
          </th>
          <th class="form-group{% if form.errors.amount_to_state_budget %} has-error{% endif %}">
            <label class="control-label" for="id_amount_to_state_budget">
              Сума, яка перераховуєть-ся до бюджету (грн)
            </label>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr class="replicator">
          <td class="form-group{% if form.errors.receipt_date %} has-error{% endif %}">
            <input type="date" class="form-control input-sm" id="id_receipt_date" name="receipt_date" />
            {% if form.errors.receipt_date %}<span class="help-block">{{ form.errors.receipt_date }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.amount %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_amount" name="amount" />
            {% if form.errors.amount %}<span class="help-block">{{ form.errors.amount }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.transaction_id %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_transaction_id" value="{{ task.params.transaction_id }}" disabled />
            {% if form.errors.transaction_id %}<span class="help-block">{{ form.errors.transaction_id }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.payee_name %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_payee_name" name="payee_name" />
            {% if form.errors.payee_name %}<span class="help-block">{{ form.errors.payee_name }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.payee_identification %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_payee_identification" name="payee_identification" />
            {% if form.errors.payee_identification %}<span class="help-block">{{ form.errors.payee_identification }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.payee_address %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_payee_address" name="payee_address" />
            {% if form.errors.payee_address %}<span class="help-block">{{ form.errors.payee_address }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.date %} has-error{% endif %}">
            <input type="date" class="form-control input-sm" id="id_date" name="date" />
            {% if form.errors.date %}<span class="help-block">{{ form.errors.date }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.document_id %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_document_id" name="document_id" />
            {% if form.errors.total_funds %}<span class="help-block">{{ form.errors.total_funds }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.explanation %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_explanation" name="explanation" />
            {% if form.errors.explanation %}<span class="help-block">{{ form.errors.explanation }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.amount_to_payee %} has-error{% endif %}">
            <input type="text" class="form-control input-sm" id="id_amount_to_payee" name="amount_to_payee" />
            {% if form.errors.amount_to_payee %}<span class="help-block">{{ form.errors.amount_to_payee }}</span>{% endif %}
          </td>
          <td class="form-group{% if form.errors.amount_to_state_budget %} has-error{% endif %}">
            <input type="text" class="form-control input-sm last" id="id_amount_to_state_budget" name="amount_to_state_budget" />
            {% if form.errors.amount_to_state_budget %}<span class="help-block">{{ form.errors.amount_to_state_budget }}</span>{% endif %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
</section>
{% endblock %}

templates/tasks/get_transaction.html
{% extends "tasks/base_form.html" %}

{% block task-form %}
<div class="form-group">
  <label for="id_transaction_date">Find transaction date</label>
  <input type="date" class="form-control" name="transaction_date" id="id_transaction_date" aria-describedby="transaction_date_help" placeholder="Enter transaction date">
  <small id="transaction_date_help" class="form-text text-muted">Some helper for this task.</small>
</div>
<div class="form-group">
  <label for="id_transaction_value">Find transaction value</label>
  <input type="text" class="form-control" name="transaction_value" id="id_transaction_value" aria-describedby="transaction_value_help" placeholder="Enter transaction value">
  <small id="transaction_value_help" class="form-text text-muted">Shouldn't contain currency and be divided by a dot. i.e. 4299.99</small>
</div>
<div class="form-group">
  <label for="id_transaction_donor">Find transaction donor</label>
  <input type="text" class="form-control" name="transaction_donor" id="id_transaction_donor" aria-describedby="transaction_donor_help" placeholder="Enter transaction donor">
  <small id="transaction_donor_help" class="form-text text-muted">First name and last name</small>
</div>
{% endblock %}

templates/tasks/get_transaction_ids.html
{% extends "tasks/base_form.html" %}

{% block task-form %}
<h3>Find transaction IDs on page {{ task.params.page }}</h3>
<h4>
  {% if task.params.transaction_type == 1 and task.params.money_destination == 1 %}
  1.1. Contributions by money to political party accounts
  {% elif task.params.transaction_type == 2 and task.params.money_destination == 1 %}
  1.2. Information on the return and transfer to the State Budget of Ukraine funds received in violation of the law on political party accounts
  {% elif task.params.transaction_type == 3 and task.params.money_destination == 1 %}
  1.3. Information on the return and transfer to the State Budget of Ukraine funds received by political parties in error
  {% elif task.params.transaction_type == 1 and task.params.money_destination == 2 %}
  1.4. Contributions by money to the accounts of the election fund of a political party
  {% elif task.params.transaction_type == 2 and task.params.money_destination == 2 %}
  1.5. Information about the return and transfer to the State Budget of Ukraine of cash received in violation of the legislation requirements on the accounts of the election fund
  {% elif task.params.transaction_type == 3 and task.params.money_destination == 2 %}
  1.6. Information about the return and transfer to the State Budget of Ukraine of cash received by mistake on the accounts of the election fund
  {% endif %}
</h4>
<h4 class="orange">
  {% if task.params.legal_identification == 1 %}
  1) from individuals
  {% elif task.params.legal_identification == 2 %}
  2) from legal entities
  {% endif %}
</h4>
<div class="form-group">
  <label class="control-label" for="id_transaction_ids">Provide transaction IDs</label>
  <input type="text"
         class="form-control"
         name="transaction_ids"
         id="id_transaction_ids"
         placeholder="Transaction IDs"
         aria-describedby="transaction_ids_help"
         required>
  {{ form.errors.transaction_ids }}
</div>
{% endblock %}